version: "3.7"
services:

  user:
    image: user:latest
    build:
      context: .
      dockerfile: src/Services/UserService/Dockerfile
      args:
        - env:${env}
        - redis:${redis}
    ports:
      - "1000"
      
  order:
    image: order:latest
    build:
      context: .
      dockerfile: src/Services/OrderService/Dockerfile
    ports:
      - "5001:80"
    depends_on:
      - user