version: "3.7"
services:

  user:
    environment:
        - port=1000
    image: user:latest
    build:
      context: .
      dockerfile: src/Services/UserService/Dockerfile
      args:
        - env:${env}
        - redis:${redis}
    ports:
      - ${port}
      
  order:
    image: order:latest
    build:
      context: .
      dockerfile: src/Services/OrderService/Dockerfile
    ports:
      - "5001:80"
    depends_on:
      - user