version: "3.7"
services:
  user:
    build:
      context: .
      dockerfile: ../src/Services/UserService/Dockerfile
    ports:
      - "5000:80"
  order:
    build:
      context: .
      dockerfile: ../src/Services/OrderService/Dockerfile
    ports:
      - "5001:80"
    depends_on:
      - user
